title: TingPing's blog
description: Development blog of TingPing
author: Patrick Griffis
email: tingping@fedoraproject.org
url: https://blog.tingping.se
github_username: TingPing
timezone: America/New_York
theme: minima
remote_theme: jekyll/minima
disqus:
  shortname: tingping
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
