title: TingPing's blog
description: Development blog of TingPing
author: Patrick Griffis
email: tingping@fedoraproject.org
url: https://blog.tingping.se
github_username: TingPing
timezone: America/New_York
# Upstream broke in https://github.com/jekyll/minima/pull/686 (on purpose until 3.0?)
remote_theme: jekyll/minima@fdc3aba23a1d59ad1d1f65f505693848c4b82fdf
minima:
  skin: dark
  social_links:
    github: TingPing
    gitlab:
      - username: pgriffis
        instance: gitlab.gnome.org
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
