title: TingPing's blog
description: Development blog of TingPing
author: Patrick Griffis
email: tingping@fedoraproject.org
url: https://tingping.github.io
github_username: TingPing
google_analytics: UA-17775794-13
theme: minima
disqus:
  shortname: tingping
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
