title: TingPing's blog
description: Development blog of TingPing
author: Patrick Griffis
email: tingping@fedoraproject.org
url: https://blog.tingping.se
github_username: TingPing
timezone: America/New_York
remote_theme: jekyll/minima@master
minima:
  skin: dark
  social_links:
    github: TingPing
    gitlab:
      - username: pgriffis
        instance: gitlab.gnome.org
disqus:
  shortname: tingping
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
